### ISSUE TITLE
Change container port

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#11]
**Is your feature request related to a problem? Please describe.**
Problems when having two Threadfin, Plex messes up

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PilaScat** [comment]
Or maybe it is another thing, the fact remains that you can't put two on plex

**Comment by marcelGoerentz** [comment]
@PilaScat Hey,

can you explain your use case please. Maybe there is another solution for your problem.
Nevertheless you can change the port of your container in your docker compose file.

    version: "2.3"
    services:
      threadfin:
        image: mgoerentz/threadfin
        container_name: threadfin
        ports:
          - 34401:34400
        environment:
          - PUID=1001
          - PGID=1001
          - TZ=America/Los_Angeles
        volumes:
          - ./data/conf:/home/threadfin/conf
          - ./data/temp:/tmp/threadfin:rw
        restart: unless-stopped


This way you will have a container where the host port will be 34401.

**Comment by PilaScat** [comment]
Yes I know, but plex cannot distinguish the two.Anyway I fixed routing threadfin1 via threadfin2On Jul 31, 2024 08:41, Marcel Goerentz ***@***.***> wrote:
@PilaScat Hey,
can you explain your use case please. Maybe there is another solution for your problem.
Nevertheless you can change the port of your container in your docker compose file.
version: "2.3"
services:
  threadfin:
    image: mgoerentz/threadfin
    container_name: threadfin
    ports:
      - 34401:34400
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - ./data/conf:/home/threadfin/conf
      - ./data/temp:/tmp/threadfin:rw
    restart: unless-stopped

**Comment by PilaScat** [comment]
Forget it, I left it working last night and now nothing is working.

**Comment by marcelGoerentz** [comment]
Ok I will close this then. Feel free to open it again.

**Comment by PilaScat** [comment]
The problem still remains, it's impossibile to add two instances to Plex, contact me on discord if you can @pilascat
