### ISSUE TITLE
Some channels works only on Windows and not in Android/TV

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#12]
**Server (please complete the following information):**
- OS Docker
- Threadfin Version and Build 1.2.3

**Additional context**
I haven't any logs for Threadfin, but 404 errors on Plex:
```
Debug — Request: [172.18.0.1:33970 (Allowed Network (Subnet))] GET /livetv/sessions/8c22f66e-9f15-4c74-8b6e-88c36e165cf8/60a7cf4cc457eadb-com-plexapp-android/index.m3u8?autoAdjustQuality=0&hasMDE=1&location=wan&mediaBufferSize=74944&offset=-1.000000 (35 live) #207f45 GZIP Signed-in Token (PilaScat) (TV Camera)
Debug — Completed: [172.18.0.1:33970] 404 GET /livetv/sessions/8c22f66e-9f15-4c74-8b6e-88c36e165cf8/60a7cf4cc457eadb-com-plexapp-android/index.m3u8?autoAdjustQuality=0&hasMDE=1&location=wan&mediaBufferSize=74944&offset=-1.000000 (35 live) #207f45 GZIP 0ms 379 bytes (pipelined: 1)
```
If you can contact me I'll show to you live, discord @pilascat
Seems that now you're the mantainer of threadfin ahah, we could make it work!

**Comment by marcelGoerentz** [comment]
For me it seems like this an issue in Plex.
Do you have any buffer activated in your Threadfin settings?
You should find the logs with this command:

    cat /var/log/syslog | grep Threadfin

But in my opinion is when Threadfin is doing it correct for the windows client then everything should be fine from Threadfin site.

**Comment by PilaScat** [comment]
Yes I'm using a buffer, do I need to see logs on Plex or Threadfin dockers?

**Comment by marcelGoerentz** [comment]
On the Threadfin container.

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/49d873fe-4c7b-4226-ac83-45c51341a626)
No syslog

EDIT: some channels starts without error but ramains black with no audio on android, on windows works

**Comment by marcelGoerentz** [comment]
Hmmmm, we need these logs to see what is happening I will check how to retrieve them.

**Comment by marcelGoerentz** [comment]
You can use:

    docker logs [Options] CONTAINER

For more details have a look here: https://docs.docker.com/reference/cli/docker/container/logs/

**Comment by PilaScat** [comment]
`FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204`
this is a long time error https://github.com/xteve-project/xTeVe/issues/227
tried removing user agent but nothing, maybe if it is empy it deafults to Threadfin

**Comment by marcelGoerentz** [comment]
Ok, interesting… I will try to fix this. What image are you using? I need to compile the binary for it und you have to put it in your container. I will ping you when I‘m ready.

**Comment by PilaScat** [comment]
Your image on docker, latest one

**Comment by marcelGoerentz** [comment]
Yeah,but there are different architectures. I assume you didn‘t use the command likes this

    docker pull --platform linux/arm64 

Hopefully I will find time in the evening to have a look into this.

**Comment by PilaScat** [comment]
Yes in fact, is amd64, if you would have a faster communication Im present on discord

**Comment by PilaScat** [comment]
Testing and testing, its very finnicky, Im getting a lots of error for you ahah

**Comment by PilaScat** [comment]
I have this strange error, before i was using threadfin via vpn connected to another threadfin who had geo blocked challenge, now is the same but I have updated the playlist but threadfin(vpn) still uses a wrong link
![image](https://github.com/user-attachments/assets/0f19e64d-4fd7-4fd0-a612-1456509c796d)
now it is 192.168.1.20:34300

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/2d1b05f8-148b-4b48-9255-2f8cbbf48fcc)
![image](https://github.com/user-attachments/assets/82ec2d73-f680-464e-bdbe-fb0d39b79178)

**Comment by marcelGoerentz** [comment]
The error 11103 is coming from the web server connection. This seems to be an issue with the connection between Web-UI and the Threadfin instance. This should not interference with the stream.

I still think this has something to do with Plex itself. I will check regarding the user_agent.

**Comment by marcelGoerentz** [comment]
So the xteve thing is already done. Have you tried to unset the user agent setting?
You are trying to proxy through a proxy? I am not sure if this is possible.
Are there any logs from the first Threadfin instance?

**Comment by PilaScat** [comment]
Already tried unsetting, no change, probably it defaults?

**Comment by marcelGoerentz** [comment]
Defaults or maybe a browser?

**Comment by PilaScat** [comment]
I don't know how to know it ahah

**Comment by marcelGoerentz** [comment]
https://useragentstring.com/

**Comment by PilaScat** [comment]
Ah, you mean to put a generic one?

**Comment by marcelGoerentz** [comment]
Yes, maybe that will help

**Comment by PilaScat** [comment]
Adding it fixed the browser playback that was not working before, then I discovered that this problem is not actually due to threadfin/plex but to replex, in fact I opened an issue here https://github.com/lostb1t/replex/issues/154
I would wait to close this issue though, the problems are not over, I would like to help fix them before the Italian Serie A starts on August 20th ahahh

**Comment by marcelGoerentz** [comment]
I understand. I've done a bit testing on my site and having a setup like this vlc -> threadfin instance 2 -> threadfin instance 1 -> original stream. And this is working without any issues. If you do not reply until 20th August I will assume that everything is fine and will then close this issue 😄

**Comment by PilaScat** [comment]
now I fixed, it was a reverse proxy problem, but now chrome doesn't play live tv 😂

**Comment by PilaScat** [comment]
for now I'll close this, and if anyone had problems add your user agent to fix

**Comment by marcelGoerentz** [comment]
Super!
