### ISSUE TITLE
Customize no more stream image

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#13]
I would like to write some instructions for my users, it would be nice

**Comment by marcelGoerentz** [comment]
Hmmm you want a costumized image that will be shown? Or did I get you wrong?

**Comment by PilaScat** [comment]
Yeah, it would be sufficient uploading it to the config folder without dialog in the webui

**Comment by marcelGoerentz** [comment]
Okay, I will check how this will be possible 😄

**Comment by marcelGoerentz** [comment]
I'm thinking about how this could be done in a good way.

The current way is that the image is saved in the source code and the base64 encoded bytes will be stored in the binary.f
I could add a function that will check if there has been placed a file in a specific folder within the configuration folder and use this one instead. But right now I'm not sure how to achieve this.

Would this be a convenient way for you?

**Comment by PilaScat** [comment]
Yes, it would be perfect

**Comment by marcelGoerentz** [comment]
The following has been shown to me, in order to use a customized no-more-stream image, it is necessary that ffmpeg / vlc is installed on the computer / container. Then the image must be converted into a video file with ffmpeg / vlc. Then I can replace the video file used by Threadfin with the newly created one.

I can make this function even easier by adding a dialog that allows the user to upload the image via the web client, and the rest is done in the backend.
Is this a better solution? I mean, I will need more time for implementation, but in the end it will be more self-explanatory and less complicated for the user.

Otherwise, the user will have to put the video file directly into a configuration folder and I will retrieve it from there. -> Much faster to implement, but it will need more description and documentation, plus there are more potential problems since the user can put any file there and I can't check everything.

Translated with DeepL.com (free version)

**Comment by PilaScat** [comment]
Since is an advanced customization it could be via file on appdata, not necessarily a dialog, probably the faster one for you is right

**Comment by marcelGoerentz** [comment]
I've pushed  a branch where the function should be already implemented, all you need to do is place the video file in the config folder:
data/videos/*

**Comment by PilaScat** [comment]
> I've pushed a branch where the function should be already implemented, all you need to do is place the video file in the config folder: data/videos/*

what format? h264? maybe ian image is more straightforward

**Comment by marcelGoerentz** [comment]
Yes h264 is good, any codec supported by mpeg-ts is acceptable. I‘ve added a readme in resources folder how to create a video from an image via vlc or femora.

**Comment by marcelGoerentz** [comment]
This is the first step to the implementation, the next will be to use a image placed by the user. 😄

**Comment by PilaScat** [comment]
In the next days I'll try, for now there's a match, I cannot test ahah

**Comment by marcelGoerentz** [comment]
No worries, if no one is complaining about the latest beta, then I will release a new beta with this code today.

**Comment by PilaScat** [comment]
I'm on stable for now

**Comment by marcelGoerentz** [comment]
Added functions to check for an image in config/data/images/costum/ and generate a video from the file with ffmpeg or vlc!

Next step will be to add the user interface in the web client.

**Comment by PilaScat** [comment]
> /costum/

/custom/ ?

**Comment by marcelGoerentz** [comment]
The name is irrelevant since threadfin will take the first file found. The complete path could be:
.threadfin/data/images/custom/img.jpg

**Comment by marcelGoerentz** [comment]
So I've also implemented the user interface in the web client. Everything can be found in the latest beta.

**Comment by PilaScat** [comment]
Perfect, I'll try soon

**Comment by marcelGoerentz** [comment]
Is everything working as expected?

Do I need to add more tips on how to import the new image?

**Comment by PilaScat** [comment]
I didn't had time to try it out, I'll keep you updated

**Comment by marcelGoerentz** [comment]
@PilaScat Did you have any time recently?
I want to push the feature to main release.

**Comment by PilaScat** [comment]
no, I'll try now

**Comment by PilaScat** [comment]
uploaded but I see the default image, even restarted threadfin
I used this
![No more streams](https://github.com/user-attachments/assets/1094ee28-8d77-4217-83b9-774aa2a7114c)

**Comment by marcelGoerentz** [comment]
Do you have log entries? I‘ll check to Night what’s going on. I didn’t had an issue when testing

**Comment by PilaScat** [comment]
> Do you have log entries? I‘ll check to Night what’s going on. I didn’t had an issue when testing

No logs

**Comment by marcelGoerentz** [comment]
I've found the bug, fixed it in the newest beta

**Comment by PilaScat** [comment]
But now there is a permission problem, all functionality is broken
I would also be fine with creating the .ts file and putting it in the folder, without having to make threadfin do extra things that could break it

**Comment by marcelGoerentz** [comment]
Aren‘t you running the latest docker build ?

**Comment by PilaScat** [comment]
> Aren‘t you running the latest docker build ?

latest beta

**Comment by marcelGoerentz** [comment]
I‘ve tested it with the beta tag. And it was working as expected. I really need to see the logs.
Nevertheless, when you have created the .ts file you can place it in the config folder under config/data/video/  Threadfin will get it from there. Just for your info, if you are placing mir then one file in that dir Threadfin will delete them.

**Comment by PilaScat** [comment]
> I‘ve tested it with the beta tag. And it was working as expected. I really need to see the logs. Nevertheless, when you have created the .ts file you can place it in the config folder under config/data/video/ Threadfin will get it from there. Just for your info, if you are placing mir then one file in that dir Threadfin will delete them.

only in beta right? because I can't test if the streams doesn't work

**Comment by marcelGoerentz** [comment]
Yes right now it’s only in the beta.

**Comment by PilaScat** [comment]
I recommend keeping it as an advanced option, without an interface, just adding the video file to the folder
whoever wants to do it will prepare the .ts file independently, maybe leaving something written in the readme
this way we avoid possible errors and waste of time since I will probably be the only one to use it 😂
thank you very much for the work you are doing

**Comment by marcelGoerentz** [comment]
No worries, the interface is just an add on 😆 The code is completely the same

**Comment by PilaScat** [comment]
I saw that in the new beta it create a user and assign it to threadfin and ffmpeg, that's what doesn't make things work, I guess it's for ffmpeg image to video encoding, but if it causes problems I'll do it from my pc then upload the video

**Comment by marcelGoerentz** [comment]
Actually it should not cause problems as all the permissions will be checked on start up. But I need to see the logs, so I know what is going wrong in your container. I‘ve set up a new container and everything was working fine.

**Comment by PilaScat** [comment]
```
2024/09/12 11:14:17 [Threadfin] Version:                1.5 Build: 0
2024/09/12 11:14:17 [Threadfin] Database Version:       0.5.0
2024/09/12 11:14:17 [Threadfin] System IP Addresses:    IPv4: 3 | IPv6: 0
2024/09/12 11:14:17 [Threadfin] Hostname:               b3a72f6b6587
2024/09/12 11:14:17 [Threadfin] System Folder:          /home/threadfin/conf/
2024/09/12 11:14:17 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
2024/09/12 11:14:17 [Threadfin] Git Branch:             Switching Git Branch to -> main
2024/09/12 11:14:17 [Threadfin] [ERROR] open /home/threadfin/conf/permission.test: permission denied (Invalid file permissions for config folder) - EC: 1015
2024/09/12 11:14:17 [Threadfin] Temporary Folder:       /tmp/threadfin/2024-07-OSF4-W9J7TW/
2024/09/12 11:14:17 [Threadfin] [ERROR] open /tmp/threadfin/2024-07-OSF4-W9J7TW/permission.test: permission denied (Invalid file permissions for temp folder) - EC: 1016
2024/09/12 11:14:17 [Threadfin] [ERROR] unlinkat /tmp/threadfin/2024-07-OSF4-W9J7TW/PIDs: permission denied () - EC: 0
Error scanning file PIDs: open /tmp/threadfin/2024-07-OSF4-W9J7TW/PIDs: permission deniedGit Branch is now: main
```
I need to reopen ahah

> > Do you have log entries? I‘ll check to Night what’s going on. I didn’t had an issue when testing
> 
> No logs

at least now I have them

**Comment by PilaScat** [comment]
for now I've rolled back to v1.4.1

**Comment by marcelGoerentz** [comment]
In my opinion you should make a back up, delete the container, pull the latest image from docker and restore your backup. Then everything should work as expected.

**Comment by PilaScat** [comment]
Did but same problem:
```
Git Branch is now: main
2024/09/13 18:16:56 [Threadfin] [ERROR] mkdir /home/threadfin/conf/backup/: permission denied (Folder could not be created.) - EC: 1070
2024/09/13 18:16:56 [Threadfin] [ERROR] mkdir /home/threadfin/conf/backup/: permission denied () - EC: 0
```

**Comment by marcelGoerentz** [comment]
Hmm, is someone else having this problem?
I will check if I can do anything to fix this…

**Comment by marcelGoerentz** [comment]
This are the log I get when creating a new container from the latest image:
```
2024-09-13 22:04:24 Git Branch is now: main
2024-09-13 22:04:24 For help run: /home/threadfin/bin/threadfin -h
2024-09-13 22:04:24 
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Version:                1.5 Build: 0
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Database Version:       0.5.0
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 1
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Hostname:               87417c7cd8b4
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] System Folder:          /home/threadfin/conf/
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Git Branch:             Switching Git Branch to -> main
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] SOURCE:                 PMS
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Temporary Folder:       /tmp/threadfin/2024-09-MQMF-TQM75Q/
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] GitHub:                 https://github.com/marcelGoerentz
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Git Branch:             Main [marcelGoerentz]
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] SSDP / DLNA:            true
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] [WARNING] Updates are disabled in the settings
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] UUID:                   2024-09-MQMF-TQM75Q
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Tuner (Plex / Emby):    1
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] EPG Source:             PMS
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Plex Channel Limit:     480
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Unfiltered Chan. Limit: 480
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] All streams:            0
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Active streams:         0
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Filter:                 0
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] DVR IP:                 127.0.0.1:34400
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Web Interface:          http://127.0.0.1:34400/web/
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] DVR IP:                 172.17.0.2:34400
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Web Interface:          http://172.17.0.2:34400/web/
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] DVR IP:                 ::1:34400
2024-09-13 22:04:24 2024/09/13 20:04:24 [Threadfin] Web Interface:          http://::1:34400/web/
```

**Comment by marcelGoerentz** [comment]
Are you able to test again with the latest beta? I've updated the image again.

**Comment by PilaScat** [comment]
il try soon, I've have a lot of exams in university ahaha
Probably there is a problem with the counter of active tuner in the playlist (it tells me no more streams but I'm using 2/3 channels)

**Comment by marcelGoerentz** [comment]
Regarding the counter that is a known issue. I would recommend to use the API. I think I will delete the counter as they are not necessary anymore with the API.

**Comment by PilaScat** [comment]
Not the web ui one

**Comment by marcelGoerentz** [comment]
It seems like I really have to rework the buffer.
It should not happen that there are streams still working when not listed.

**Comment by PilaScat** [comment]
API? Where can I change?
I pay 3 streams to my m3u, I would like to use them ahahha

**Comment by PilaScat** [comment]
with the latest beta:
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "${THREADFIN_BIN}": executable file not found in $PATH: unknown.`

**Comment by marcelGoerentz** [comment]
Which docker version are you running? I’ve tried with latest and there is no issue.

**Comment by PilaScat** [comment]
24.0.9, latest unraid stable

**Comment by PilaScat** [comment]
any news? one of my instance keep doing memory leaks all over, now I limited eith docker --memory=8g --kernel-memory=8g
And could you merge with the new version from original project?

**Comment by marcelGoerentz** [comment]
Hey,
I was on vacation, I can try to merge with original one but that will take some time that I don’t have.

**Comment by PilaScat** [comment]
Hi, take your time, no problem, I saw there was a lot of fixes in the new releases of the official

**Comment by PilaScat** [comment]
maybe you could try merging with the official project and work on only one, so its less work and more bugfixes and features, its a win win

**Comment by marcelGoerentz** [comment]
I tried that at the start of this project. Unfortunately the maintainer was not interested in my contribution.

**Comment by PilaScat** [comment]
anyway im still on 1.4.1, I tried even to create a new container but without success, there is a problem with permissions:
```
Git Branch is now: main
2024/10/17 00:41:05 [Threadfin] [ERROR] mkdir /home/threadfin/conf/backup/: permission denied (Folder could not be created.) - EC: 1070
2024/10/17 00:41:05 [Threadfin] [ERROR] mkdir /home/threadfin/conf/backup/: permission denied () - EC: 0
```

**Comment by marcelGoerentz** [comment]
Does the backup folder already exists?
You can try to run the docker container and then from the command line run this command:

```
   docker exec -it <container name or ID> /bin/sh
```

And then in the shell:
```
    ls -al conf
```


Please try again with latest beta

**Comment by PilaScat** [comment]
> ```
>    docker exec -it <container name or ID> /bin/sh
> ```

Cannot try this, the container is restarting endlessy

```
2024/11/06 16:33:02 [Threadfin] Version:                1.6 Build: 0
2024/11/06 16:33:02 [Threadfin] Database Version:       0.5.0
2024/11/06 16:33:02 [Threadfin] System IP Addresses:    IPv4: 3 | IPv6: 1
2024/11/06 16:33:02 [Threadfin] Hostname:               7d3bb1877fd5
2024/11/06 16:33:02 [Threadfin] System Folder:          /home/threadfin/conf/
2024/11/06 16:33:02 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
2024/11/06 16:33:02 [Threadfin] Git Branch:             Switching Git Branch to -> main
2024/11/06 16:33:02 [Threadfin] [ERROR] open /home/threadfin/conf/permission.test: permission denied (Invalid file permissions for config folder) - EC: 1015
2024/11/06 16:33:02 [Threadfin] Temporary Folder:       /tmp/threadfin/2024-07-OSF4-W9J7TW/
2024/11/06 16:33:02 [Threadfin] [ERROR] open /tmp/threadfin/2024-07-OSF4-W9J7TW/permission.test: permission denied (Invalid file permissions for temp folder) - EC: 1016
2024/11/06 16:33:02 [Threadfin] [ERROR] unlinkat /tmp/threadfin/2024-07-OSF4-W9J7TW/PIDs: permission denied () - EC: 0
Error scanning file PIDs: open /tmp/threadfin/2024-07-OSF4-W9J7TW/PIDs: permission deniedGit Branch is now: main
```

**Comment by PilaScat** [comment]
seems fixed on 1.6.1, but the custom image is not working sadly

**Comment by PilaScat** [comment]
I don't see any logs when uploading the image via the web menu

**Comment by marcelGoerentz** [comment]
Currently there are no debug messages, will add them in the next beta.

**Comment by PilaScat** [comment]
I saw that the custom image/video is there in the folder, but it doesn't use it

**Comment by marcelGoerentz** [comment]
That is really strange, I will check what can go wrong there. Have you used vlc or ffmpeg to create the file?

**Comment by PilaScat** [comment]
no, uploaded only via webui

**Comment by marcelGoerentz** [comment]
But do you use vlc or ffmpeg in the buffer settings?
This is the only way to create the video file after the web upload.

**Comment by PilaScat** [comment]
ffmpeg

**Comment by marcelGoerentz** [comment]
Should be fixed in latest beta.

**Comment by PilaScat** [comment]
it works, but the video is not looped, so when those few seconds pass the channel closes

**Comment by marcelGoerentz** [comment]
That is correct, I can extend the duration. But it should not be too long.
I will do this with the next release.

**Comment by marcelGoerentz** [comment]
Checkout the latest release.

**Comment by PilaScat** [comment]
seems ok
