### ISSUE TITLE
Could you sync working changes from official repository?

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#14]
I thought it was dead

**Comment by marcelGoerentz** [comment]
I will check what has been changed and sync where possible.

**Comment by PilaScat** [comment]
Thanks, best of both worlds ahah

**Comment by marcelGoerentz** [comment]
Hey, there will be a new beta in a few minutes!

**Comment by PilaScat** [comment]
news?

**Comment by marcelGoerentz** [comment]
In beta everything should be synced.
I‘m currently working on the enhancement. When everything is working as expected I will push a new release.

**Comment by PilaScat** [comment]
Didn't saw the release, I have this bug:
![image](https://github.com/user-attachments/assets/87bf477f-677e-418a-8b12-53eda7b42292)

**Comment by marcelGoerentz** [comment]
Seems like the muxer does not like the argument. Do you now the codecs of the stream?

**Comment by PilaScat** [comment]
he does it with everyone, anyway .m3u8
edit: wait for the codecs, everyone is different, but none works
![image](https://github.com/user-attachments/assets/0600b680-a511-440f-8ff3-9455424ae3b4)
I think there's an error when passing the string to ffmpeg

**Comment by marcelGoerentz** [comment]
I also think there is an error, this was introduced with the new functions I‘ve synced.

**Comment by PilaScat** [comment]
Be aware in another bug with the original project, the counter of active streams is broken

**Comment by marcelGoerentz** [comment]
> I also think there is an error, this was introduced with the new functions I‘ve synced.

I found the error to this and it will be fixed in next beta! There was a typo in the arguments for ffmpeg.



> Be aware in another bug with the original project, the counter of active streams is broken

Can you explain what exactly is broken so I can have a deeper look into it?

**Comment by PilaScat** [comment]
> > Be aware in another bug with the original project, the counter of active streams is broken
> 
> Can you explain what exactly is broken so I can have a deeper look into it?

It counts backwards 😂

There's  another problem, streams doesn't work at all
![image](https://github.com/user-attachments/assets/65383f29-e957-406c-9bb3-08fff50f9fef)
![image](https://github.com/user-attachments/assets/a5ea57cb-34fb-4c20-b11f-c2dc37a85f07)
Probabilbly is about the ip, it need to be the external, not the internal one, like 192.168.1.20 instead
Even though it worked like this before anyway

**Comment by marcelGoerentz** [comment]
Good hint I will take a look at it.

**Comment by marcelGoerentz** [comment]
Latest beta build should work now!

**Comment by PilaScat** [comment]
ill try now

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/e3e7d756-ef19-4c39-affe-f9d445f24906)
same problem

**Comment by marcelGoerentz** [comment]
Are you sure you are using the latest beta? This options are not existing anymore.

**Comment by PilaScat** [comment]
> Are you sure you are using the latest beta? This options are not existing anymore.

Sorry, it was cached, updated with Threadfin:beta docker image but it tells this
![image](https://github.com/user-attachments/assets/a1e33314-4eef-4f78-902d-432621fa914f)
It works but I don't know if I'm testing the beta, the counter disappeared

**Comment by marcelGoerentz** [comment]
This is the main branch 😟 
Maybe I need to check my Docker container

**Comment by marcelGoerentz** [comment]
Version should be 1.2 Build 4-beta

**Comment by PilaScat** [comment]
and probably in the 1.2.3 version there was a memory leak, I forgot to tell you 😂
if it happens again with the new version I'll tell you, it made my entire server crash for a day ahha

**Comment by PilaScat** [comment]
> Version should be 1.2 Build 4-beta

maybe it's because you went back in version from what I saw in the commit

**Comment by marcelGoerentz** [comment]
Could be but should not be 🥲

**Comment by marcelGoerentz** [comment]
Okay, the error is in my  Dockerfile 😢 
I need to check how I can fix it

**Comment by marcelGoerentz** [comment]
Okay next beta release should be working!

**Comment by marcelGoerentz** [comment]
Sorry there is an issue with the beta release yaml file also.

**Comment by PilaScat** [comment]
I'll wait, tell me when its ready

**Comment by marcelGoerentz** [comment]
> I'll wait, tell me when its ready

Sorry for the circumstances...
The next beta release should really fix everything 😄

**Comment by PilaScat** [comment]
No problem

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/c4a8fc00-66ad-498d-9ede-2116e0080377)
why it says this ip? unreachable from plex, but reachable from webui at 192.168.1.20:34400
fixed setting via threadfin domain, but it shouldn't be necessary

**Comment by marcelGoerentz** [comment]
Well Threadfin takes the first IP it finds.
Running in a docker container it will take the containers IP. Defining the domain will make it accessible from outside the docker container with the correct FQDN or IP. I will fix this in docu / tool tip as soon as possible!

**Comment by marcelGoerentz** [comment]
By said this, it is necessary to set the domain for Docker users
Nevertheless, if the listening IP option hasn't been used the Threadfin will be reachable over the host interface with the given port.

**Comment by PilaScat** [comment]
> Well Threadfin takes the first IP it finds. Running in a docker container it will take the containers IP. Defining the domain will make it accessible from outside the docker container with the correct FQDN or IP. I will fix this in docu / tool tip as soon as possible!

I know but in reality his ip in the docker network is 172.18.0.xx
I don't know where he found the 10.5.0.2 ahhaha

anyway fixed this seems perfect, I'll try to keep it open for some hours to test stability

**Comment by marcelGoerentz** [comment]
> I don't know where he found the 10.5.0.2 ahhaha

Me neither 🤣

**Comment by PilaScat** [comment]
anyway in my opinion it is already stable for main branch

**Comment by marcelGoerentz** [comment]
Great to hear! I will push it to main tonight. I already have another feature ready that will store the created PIDs and kill all processes that have been left at the next start of the software! This will be pushed to beta afterward.
Then I will begin with the customization No more streams thing :)

**Comment by PilaScat** [comment]
perfect
