### ISSUE TITLE
New version alert appearing even on the latest version.

### ISSUE THREAD

**Issue by Renkyz** [marcelGoerentz/Threadfin#19]
This issue existed on 1.2.3 as well, but I just updated to 1.2.4 and it's still there.
"Neue Version verfügbar! Klicken Sie hier, um sie herunterzuladen." appears at the top of the web interface even when running the latest version. Not a big deal but figured I'd mention it.

**Comment by marcelGoerentz** [comment]
Already saw that, currently fixing it :)

**Comment by marcelGoerentz** [comment]
Should be fixed with next release!
https://github.com/marcelGoerentz/Threadfin/commit/e1d7b74917555fdc1864c4e61ba744ffa3ab1c45

**Comment by Renkyz** [comment]
Cool :)

**Comment by Renkyz** [comment]
![Capture](https://github.com/user-attachments/assets/a8fbfef1-afd7-430e-8a86-386df46a13fa)

**Comment by Renkyz** [comment]
At first launch of v1.2.5 the alert was gone. But once I refreshed the tab it came back and I see a new error.

**Comment by Renkyz** [comment]
@marcelGoerentz

**Comment by marcelGoerentz** [comment]
I will have a look on this

**Comment by Renkyz** [comment]
Cheers. If there is any info you'd like me to provide from my settings that will help diagnose it, just let me know :)

**Comment by marcelGoerentz** [comment]
I think I already fixed it 😄
Next version should not show the banner unless there is a new version

**Comment by Renkyz** [comment]
Nice! Thanks again mate :)

**Comment by marcelGoerentz** [comment]
Please close the issue if the banner is not appearing anymore

**Comment by Renkyz** [comment]
Seems fixed for me now. Thanks again mate :)

**Comment by marcelGoerentz** [comment]
You are welcome, thanks for the feedback.
