### ISSUE TITLE
Cannot get images from imgur

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#24]
Latest version, I can't reach imgur anymore and so I'm without channel icons on both threadfin and plex, it happened a couple of days ago (I have automatic updates)
![image](https://github.com/user-attachments/assets/2824b7cf-7634-46a2-8d6e-a977ffaa14b3)

**Comment by marcelGoerentz** [comment]
I didn‘t change anything regarding the images. So it must be an issue outside of Threadfin.

**Comment by PilaScat** [comment]
Strange, from the host I can get to it

**Comment by PilaScat** [comment]
Dont know why and when but it fixed itself
