### ISSUE TITLE
Too RAM hungry

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#25]
Even when it does nothing it consumes 20+ gb, I have to restart it once a day to avoid the server crashing 😂

**Comment by marcelGoerentz** [comment]
Seems like the processes are not closed correctly. Can you send a screenshot of the processes before you restart? (I need to know which process is taking most of the ram)

**Comment by PilaScat** [comment]
I have 2 instances
![image](https://github.com/user-attachments/assets/f8a05854-4f32-4ac9-8da5-1fcaa84cb171)
No one using it, and still this:
![image](https://github.com/user-attachments/assets/8ccf47b4-3c11-4f8d-9e42-4a7150a9a26e)

**Comment by marcelGoerentz** [comment]
Okay this is strange, I think have to improve my kill function for alpine linux. I will ping you when I‘ve created a new beta to test against the current version.

**Comment by marcelGoerentz** [comment]
But when threading is consuming cpu time it seems like there is a running connection. How do you verify that there is no connection to your instance? No running vlc or ffmpeg process?

**Comment by PilaScat** [comment]
> How do you verify that there is no connection to your instance?

via tautulli and watching logs

**Comment by PilaScat** [comment]
server crashed now for this

**Comment by marcelGoerentz** [comment]
I will try fix as soon as possible

**Comment by marcelGoerentz** [comment]
Should be fixed in v1.3.3

**Comment by PilaScat** [comment]
updated, will see how it goes

**Comment by marcelGoerentz** [comment]
And is it fixed now?
Would be great if there are no issues anymore with the RAM.

**Comment by PilaScat** [comment]
it seems

**Comment by marcelGoerentz** [comment]
Great to hear! You can close the issue whenever you want.
