### ISSUE TITLE
Page with channels in use

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#28]
I would like to have a page without login where I can see a list of channels in use updated live? Would it be possible?

**Comment by marcelGoerentz** [comment]
It is not impossible and I think it should not be to hard to implement the feature. But, to be honest, I don‘t know when I will have time for it.

**Comment by marcelGoerentz** [comment]
So, I don't think that without login would be a good idea 😆 
I can extend the API, so you can retrieve a list of the channels in use.
Then you will be able to use it programmatically to do whatever you want.

**Comment by PilaScat** [comment]
Would be perfect

**Comment by marcelGoerentz** [comment]
Are there specific information that you want to get also within the response?

**Comment by PilaScat** [comment]
Only a list with channels in use per playlist

**Comment by marcelGoerentz** [comment]
Okay I got you. I don‘t know when I‘ve time but I will ping you when there is something you can test.

**Comment by marcelGoerentz** [comment]
So the feature is ready to test. But I need your confirmation on the other first #13  😆 
Afterward I will push it to beta, so it will be available for testing.

**Comment by PilaScat** [comment]
hi, what is the api link?

**Comment by marcelGoerentz** [comment]
https://github.com/marcelGoerentz/Threadfin/wiki/API

**Comment by PilaScat** [comment]
I had an idea before, it would be very convenient to have a default channel like 0 that broadcasts the channels in use, do you think it is feasible now that there is already a script to get them?

**Comment by marcelGoerentz** [comment]
Oh I’m not sure, I am really not deep enough into creating a video stream with written text only. But I think it is possible. But you will need to find someone who is capable to implement it.

**Comment by PilaScat** [comment]
ahahah, I am undecided whether to create a telegram bot for this or study ffmpeg to implement this
I don't know which is simpler, surely the cleanest would be the channel
