### ISSUE TITLE
Running the latest Alpha version 1.7.0 incorrectly prompts the user to update

### ISSUE THREAD

**Issue by Renkyz** [marcelGoerentz/Threadfin#38]
Windows Server 2022 natibely running the latest alpha version amd64.exe
Ever since it was released, my latest beta version was informing me to update, so I updated to the Alpha 1.7.0 and I still get asked to update haha.
Only a minor issue but wanted to report it anyway as I'm sure it's a simple fix.

**Comment by marcelGoerentz** [comment]
Yes, this is a small fix. Will do it for the next version.

**Comment by marcelGoerentz** [comment]
Should be fixed in latest beta now!

**Comment by Renkyz** [comment]
Forgot to respond to this at the beginning of my day. Confirming it is fixed and closing the issue :)
