### ISSUE TITLE
The Web Interface seems to be broken for beta v1.7.5 on Windows.

### ISSUE THREAD

**Issue by Renkyz** [marcelGoerentz/Threadfin#39]
Pretty much as the title says. Just update from 1.7.4 to 1.7.5 and now the web interface doesn't work. As far as I can tell, loading channels still works but that's it.

**Comment by marcelGoerentz** [comment]
You are right, I will check this immediately.

**Comment by marcelGoerentz** [comment]
Fixed in v1.7.6.

**Comment by Renkyz** [comment]
Thanks for the speedy fix as usual mate :) Successfully running it now.
