### ISSUE TITLE
Is Threadfin the new buffer you're working on?

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#40]
![image](https://github.com/user-attachments/assets/e7aa9531-c759-4f36-a5c6-70463bb60b13)
Is it any better than ffmpeg?
And is it taylored for Plex?

**Comment by marcelGoerentz** [comment]
No it’s not better than ffmpeg. It can only provide media streams and buffers them. If there is a playlist in between it will fail. My recommendation is ffmpeg!

The new buffer implementation is with ffmpeg. fffmpeg will download and demux the stream, threadfin will buffer this output and serve the stream to the connected clients.

**Comment by marcelGoerentz** [comment]
I have rewritten the hole data structure of the buffer and the connected clients and the provided stream.

Now
There should be no more data leaks and everything should run a bit smoother.

**Comment by PilaScat** [comment]
> I have rewritten the hole data structure of the buffer and the connected clients and the provided stream.
> 
> Now
> There should be no more data leaks and everything should run a bit smoother.

Even with ffmpeg? or do you recommend using your new buffer?

**Comment by marcelGoerentz** [comment]
Even with ffmpeg. The buffer that I’ve rewritten is independent of the selected buffer. For VLC, FFMPEG and the Threadfin buffer the stream will be downloaded and saved to RAM / disk, this is the actual buffering. Then it will be taken from Threadfin to be send to the connected clients.
