### ISSUE TITLE
BUG: checking for remote address instead of local address

### ISSUE THREAD

**Issue by SjoerdV** [marcelGoerentz/Threadfin#6]
This will give an error based on the remote address (connecting party) instead of the local address (listening party)
https://github.com/marcelGoerentz/Threadfin/blob/5fd40f63a57cbae968f2647636afbeaf2cd49dc3/src/webserver.go#L96

**Comment by SjoerdV** [comment]
Great piece of work redoing some of the network code BTW!

**Comment by marcelGoerentz** [comment]
@SjoerdV Thank you for your feedback. In the next release it will be fixed.

**Comment by marcelGoerentz** [comment]
@SjoerdV Do you have a situation where the error happens? Unfortunately I don't get your point.
The webserver is running and everything works as expected.

**Comment by SjoerdV** [comment]
> @SjoerdV Do you have a situation where the error happens? Unfortunately I don't get your point.
> 
> The webserver is running and everything works as expected.

@marcelGoerentz It only occurs when explicit bindings are set in settings (the ;-separated list). Then if you connect from another machine to one of the bindings, the error is logged about the 'restricted ip' and access is forbidden 403.

This issue will not occur when there are no explicit bindings set NOR when you connect locally.

**Comment by marcelGoerentz** [comment]
Thank you. I will investigate it and fix it as soon as possible. The function is aiming for restricting the access to only via the given addresses. Even FQDN should work.

**Comment by marcelGoerentz** [comment]
I've created a new beta release, please cross check if this will fix the bug 😄

**Comment by marcelGoerentz** [comment]
Sorry I found a better solution and created a new beta release where it should be fixed also 😆

**Comment by SjoerdV** [comment]
> Sorry I found a better solution and created a new beta release where it should be fixed also 😆

@marcelGoerentz That works like a charm (HTTPS mode with TLS 1.3), in the case I actually put in some specific listeningIps in. 

However, leaving this list empty will return a `SSL_ERROR_RX_RECORD_TOO_LONG` (Firefox) or SSL_Protocol_Error (Other Browser) message when TLS (HTTPS) on a non-default (something else then 443) port is used (both using direct Ip and hostname). I didn't actually test running on port 443... It feels kind of weird using that port will also allow for the unsecured http protocol.
Works fine with just the unsecured channel, of course.

Maybe some updated SSL/TLS libraries or nginx headers? (Just guessing)

**Comment by marcelGoerentz** [comment]
Hmmm, die you add the key and certificate file in the config folder?

So I will close this bug as it is fixed and make Release version.

**Comment by marcelGoerentz** [comment]
@SjoerdV Ah sorry, I think I know whats going on there I will fix that asap. And create a new release since this a no brainer.

**Comment by SjoerdV** [comment]
> Hmmm, die you add the key and certificate file in the config folder?
> 
> So I will close this bug as it is fixed and make Release version.

@marcelGoerentz Great! I just saw the banner in the WebUI and shortly after that I got the same SSL_ERROR_RX_RECORD_TOO_LONG error without changing any settings.
Was your banner using an unsecured http endpoint by any chance? Or forgot to add ssl to the listener when useHttps was selected?
Reference: https://stackoverflow.com/a/69852380

**Comment by SjoerdV** [comment]
> > Hmmm, die you add the key and certificate file in the config folder?
> > So I will close this bug as it is fixed and make Release version.
> 
> @marcelGoerentz Great! I just saw the banner in the WebUI and shortly after that I got the same SSL_ERROR_RX_RECORD_TOO_LONG error without changing any settings. Was your banner using an unsecured http endpoint by any chance? Or forgot to add ssl to the listener when useHttps was selected? Reference: https://stackoverflow.com/a/69852380

So it ended up being a settings change anyway... the useHttps option only works when run through the  command line, it can not be set in the settings page. although it seems to be saved.
Thanks again for this great app!
